# Generated by Django 5.1.1 on 2024-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_venta', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('hora', models.CharField(max_length=10)),
                ('id_producto', models.IntegerField(max_length=11)),
                ('id_cliente', models.IntegerField(max_length=11)),
                ('id_trabajador', models.IntegerField(max_length=11)),
                ('cantidad', models.IntegerField(max_length=6)),
                ('registro', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
            ],
        ),
    ]
