# Generated by Django 5.1.1 on 2024-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id_ingrediente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=45)),
                ('caducidad', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(max_length=10)),
                ('id_sucursal', models.IntegerField(max_length=11)),
            ],
        ),
    ]
