# Generated by Django 5.1.1 on 2024-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=45)),
                ('horarios', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField(max_length=10)),
            ],
        ),
    ]
