# Generated by Django 5.1 on 2024-11-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('horarios', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
